# Generated by Django 2.0.8 on 2018-10-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='otkliks',
            field=models.IntegerField(choices=[(0, 'Полное фуфло'), (1, 'Так себе'), (2, 'Супер!')], default=1),
        ),
    ]
